# Generated by Django 3.1.7 on 2021-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorythm',
            name='key',
        ),
        migrations.AddField(
            model_name='algorythm',
            name='key_opts',
            field=models.TextField(default='{}'),
        ),
    ]
