# Generated by Django 3.1.1 on 2021-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20210221_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorythm',
            name='no_alphabet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='algorythm',
            name='key_opts',
            field=models.TextField(default='[]'),
        ),
    ]
