# Generated by Django 3.1.1 on 2021-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_algorythm_algo_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorythm',
            name='type',
            field=models.CharField(choices=[('C', 'Шифр'), ('S', 'Цифровая подпись'), ('K', 'Обмен ключами')], default='C', max_length=1),
        ),
    ]
